name: linters
on: [push, pull_request]
jobs:
  nix_parsing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
      - name: Check Nix parsing
        run: |
          find . -name "*.nix" -a \! -path "./secrets/*" -exec nix-instantiate --parse --quiet {} >/dev/null +
  nix_formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Check Nix formatting
        run: |
          nix-shell -p nixfmt --run 'find . -name "*.nix" -a \! -path "./secrets/*" -exec nixfmt --check {} \;'
