name: update-sources
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - name: Update flake.lock
        run: nix flake update
      - name: Commit flake.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update flake.lock
      - name: Build kernel-overlay
        run: nix build .#kernel-overlay
      - name: Update sources
        run: ./result/bin/kernel-overlay update-sources
      - name: Update workflow
        run: ./result/bin/kernel-overlay update-workflow
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update sources.json and workflow
